### ISSUE TITLE
哈啰出行 - 上海/杭州 - 资深 - 25k~35k

### ISSUE THREAD

**Issue by yygmind** [Advanced-Frontend/BetterJob-of-Frontend#1]
## 公司名称
哈啰出行
<br/>

## 工作地点
上海市、杭州市
<br/>

## 岗位级别
资深
<br/>

## 薪资范围
25k ~ 35k
<br/>

## 工作职责
岗位职责:

1. 参与web移动端、支付宝小程序、微信小程序、后台支撑系统的需求讨论和研发
2. 参与设计并实现前端开发工具
3. 发现并解决项目中、工作中的痛点
4. 引入新技术，并能推动新技术的落地
<br/>

## 任职资格

任职要求:

1. 至少熟悉React/Angular/Vue等其中一种主流的前端框架；遵守前端开发规范
2. 3年或以上的Web前端开发经验，了解http协议的基本原理，对web性能优化、常见漏洞有所的理解，并能够在工作中进行问题定位和解决过程实践
3. 掌握git做版本控制
4. 具备辅导他人的能力和技能，有良好的分享习惯。
5. 良好的沟通协作能力，并能推动项目的前进

加分项：

1. 熟悉node开发，能够开发node web, node cli, node desktop等类型的应用
2. 熟悉linux及操作系统概念。

<br/>

## 联系方式
邮箱：yyg204731@gmail.com
<br/>

**Comment by luanxuechao** [comment]
mark一下,等node 职位
