### ISSUE TITLE
杭州 阿里巴巴-天猫超市 诚招前端 20k-40k

### ISSUE THREAD

**Issue by wisdommm** [Advanced-Frontend/BetterJob-of-Frontend#11]
地点在杭州西溪园区，独立bu 天猫超市，发展好潜力打，有意向的欢迎简历 wanyan.hzh@alibaba-inc.com

**Comment by wisdommm** [comment]
天猫超市事业群致力于创造消费者可感知的价值，超越过往线上的工作方式，融入线下的“新蓝海”，将与阿里大生态内的大卖场和超市等业态的合作火爆携手，共同实现“天下超市”的理想。在天猫超市终端技术团队，你将有机会应用最先进的跨容器、高性能、智能化的大前端研发技术，从C端无线导购到B端供应链运营中后台全链路，打造线上线下一体化新零售交互体验，每年还可以参与全球瞩目的双11狂欢节，加入尽情施展才华的舞台。

1、业务领域 —— 建设天猫超市从消费者端到中后台运营系统全链路各类产品，参与每年全球瞩目双11狂欢节，加入尽情施展才华的舞台；

2、技术驱动 —— 从极致的Mobile体验、模块化工程化开发、企业级中台应用、可视化编程等等，拥有足够的挑战及机遇。

职位描述
1、精通前端技术（包括HTML/CSS/JavaScript等），熟悉ES6语法，具备跨终端（Mobile+PC）的前端开发能力，熟悉网络协议（HTTP/SSL），熟悉常见安全问题和对策；

2、 熟悉前端工程化与模块化开发，并有实践经验（如gulp/webpack、VueJS/React等），追求极致的性能与高效的研发效率；

3、 至少熟悉一门非前端的语言（如NodeJS/Java/PHP/C/C++/Python/Ruby等），并有实践经验；

4、对前端技术有持续的热情，良好的团队协作能力，提升团队研发效率，实现极致性能，通过创新交互优化产品体验；

5、加分项：具备客户端能力或者Native&Web技术融合经验；复杂企业后台应用开发经验；数据可视化产品设计开发经验；大规模/高负载场景下NodeJS应用开发、运维经验；良好的算法背景，对机器学习有研究和项目实施经验；有独立的开源项目或者参与知名开源项目经验；团队管理能力。

**Comment by yygmind** [comment]
麻烦按照要求填写
