### ISSUE TITLE
哈啰出行 - 上海 - 资深+专家 - 面议

### ISSUE THREAD

**Issue by chenwenbo** [Advanced-Frontend/BetterJob-of-Frontend#30]
## 公司名称
哈啰出行
<br/>

## 工作地点
上海闵行区秀文路898号西子国际中心
<br/>

## 薪资范围

面议
<br/>

## 岗位级别

资深 + 专家
<br/>

## 工作职责
岗位职责：
1. 负责整体技术框架、澄清技术细节、解决技术难点；
2. 完成需求评估、业务建模、系统设计，撰写相关技术文档；
3. 完成系统核心模块开发、维护，按计划完成各个模块日常开发工作；
4. 参与系统架构设计、优化；
5. 保证产品质量、扩展性、维护性和开发人员的开发效率和开发规范；

<br/>

## 任职资格
1. 本科及以上学历，5年以上Java 开发经验，能独立进行项目开发；
2. 深入掌握面向对象技术和设计模式，数据结构和算法，对DDD有深刻理解和实践的优先；
3. 熟练掌握多线程开发技术，熟悉linux环境及linux下的分布式、负载均衡、缓存、消息队列等方案；
4. 熟悉分布式, 缓存, 消息通信等机制; 能对分布式常用技术进行合理应用, 解决问题；
5. 熟练掌握 MySQL、PG数据库等数据库开发技术以及相关的调优策略；
6. 熟练使用spring, mybatis 等开源框架进行开发
<br/>

## 联系方式

wechat:chenwenbo168
<br/>

## 站外链接

<br/>

**Comment by yygmind** [comment]
老哥，这是前端区
